// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://hjwocoqipxrqkyhnmcuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqd29jb3FpcHhycWt5aG5tY3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTAxNTIsImV4cCI6MjA2NDE2NjE1Mn0.tk6BFwbIkTtFc53drrb6XQtOx3XYRQ_W4CfZ-yZtxdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);